[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"  # change to "build" if your framework uses that folder

[[redirects]]
  from = "/api/*"
  to = "https://backend.bizzwiz.ai/public/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
